# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre: #nom du filtre
            quality: 75 #taux de compression
            filters: 
                thumbnail:
                    size: [200, 200]
                    mode: outbound
        echelle: 
            quality: 85
            filters:
                scale:
                    dim: [250, 250]
        article: 
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                watermark_image:
                    image: "%kernel.project_dir%/public/img/watermark.png"
                    size: 0.1
                    position: center
